// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcj9lRpWB89iKQFmHyNxHi6Cr-PbyGHp4',
    appId: '1:285088359488:web:592e496bb02b9763b9eba5',
    messagingSenderId: '285088359488',
    projectId: 'medtrack-5afb4',
    authDomain: 'medtrack-5afb4.firebaseapp.com',
    storageBucket: 'medtrack-5afb4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGKJL9VwbduMmOcl0esLMr1k0XXkeeiRU',
    appId: '1:285088359488:android:a52238254b16b408b9eba5',
    messagingSenderId: '285088359488',
    projectId: 'medtrack-5afb4',
    storageBucket: 'medtrack-5afb4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBA3qNaEt-XlGPup3cHBEfiwQzdggXvukM',
    appId: '1:285088359488:ios:05175457c16b51d8b9eba5',
    messagingSenderId: '285088359488',
    projectId: 'medtrack-5afb4',
    storageBucket: 'medtrack-5afb4.firebasestorage.app',
    iosBundleId: 'com.example.medtrackApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBA3qNaEt-XlGPup3cHBEfiwQzdggXvukM',
    appId: '1:285088359488:ios:05175457c16b51d8b9eba5',
    messagingSenderId: '285088359488',
    projectId: 'medtrack-5afb4',
    storageBucket: 'medtrack-5afb4.firebasestorage.app',
    iosBundleId: 'com.example.medtrackApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcj9lRpWB89iKQFmHyNxHi6Cr-PbyGHp4',
    appId: '1:285088359488:web:aa9a1638c827e476b9eba5',
    messagingSenderId: '285088359488',
    projectId: 'medtrack-5afb4',
    authDomain: 'medtrack-5afb4.firebaseapp.com',
    storageBucket: 'medtrack-5afb4.firebasestorage.app',
  );
}
